/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_secmem232_phonetop_android_natives_InputHandler */

#ifndef _Included_org_secmem232_phonetop_android_natives_InputHandler
#define _Included_org_secmem232_phonetop_android_natives_InputHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef org_secmem232_phonetop_android_natives_InputHandler_DIMENSION
#define org_secmem232_phonetop_android_natives_InputHandler_DIMENSION 4096L
#undef org_secmem232_phonetop_android_natives_InputHandler_HALF_DIMENSION
#define org_secmem232_phonetop_android_natives_InputHandler_HALF_DIMENSION 2048L

JNIEXPORT jboolean JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_openInputDevice
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jboolean JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_openInputDeviceWithoutPermission
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_closeInputDevice
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_closeInputDeviceWithoutRevertPermission
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_keyDown
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_keyUp
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_keyStroke
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_touchDown
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_touchUp
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_touchSetPtr
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_sendEvent
  (JNIEnv *, jobject, jint, jint, jint);

JNIEXPORT void JNICALL Java_org_secmem232_phonetop_android_natives_InputHandler_sendEventByLow
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
