#!/bin/sh
#This Script is Run PhoneTopMiddleServer
echo 'PhoneTop Client Running Wait...'
/home/youngsick/git/Phonetop/phonetopclient/killPhoneTopClient
/home/youngsick/git/Phonetop/phonetopclient/ic
/bin/echo test > /home/youngsick/git/Phonetop/phonetopclient/testfile
echo 'PhoneTop Client Run !'